# https://travis-ci.org/spyder-ide/spyder

language: python
dist: trusty
sudo: false
env:
  global:
    - CI_PYTEST: "true"

matrix:
  fast_finish: true
  include:
    - python: "3.6"
      env: USE_CONDA=yes PYTHON_VERSION=3.6
      os: osx
      language: generic
    - python: "2.7"
      env: USE_CONDA=yes PYTHON_VERSION=2.7
      os: osx
      language: generic
    - env: USE_CONDA=yes PYTHON_VERSION=3.7
      os: linux
      language: generic
    - python: "3.6"
      env: USE_CONDA=yes
      os: linux
    - python: "3.6"
      env: USE_CONDA=no
      os: linux

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  # Avoid annoying focus problems when running tests
  # See discussion in e.g. https://github.com/spyder-ide/spyder/pull/6132
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y matchbox-window-manager; fi

install:
  - ./continuous_integration/posix/install.sh;
  - ./continuous_integration/posix/install-qt.sh;
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then DISPLAY=:99 matchbox-window-manager& fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 5; fi

script:
  - ./continuous_integration/posix/runtests.sh || ./continuous_integration/posix/runtests.sh || ./continuous_integration/posix/runtests.sh;

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source $HOME/miniconda/etc/profile.d/conda.sh && conda activate test && coveralls; fi
